import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Leaf, MapPin, Package, Snowflake, Store } from "lucide-react";

export const metadata: Metadata = {
  title: "Concept Buyer Kit | Brandform Studio",
  description: "A fictional retail buyer-kit demonstration created by Brandform Studio.",
  alternates: { canonical: "/buyer-kit" },
  robots: { index: false, follow: false },
};

const products = [
  { name: "Wild Strawberry", color: "#ed6d78", accent: "#ffd5d8", ean: "735 012 450 101 7", format: "500 ml", case: "6 × 500 ml", note: "Bright berries, clean finish", vegan: false },
  { name: "Brown Butter", color: "#c9954e", accent: "#ffe2b2", ean: "735 012 450 102 4", format: "500 ml", case: "6 × 500 ml", note: "Toasty, salted, deeply creamy", vegan: false },
  { name: "Forest Blueberry", color: "#526bb6", accent: "#d6ddff", ean: "735 012 450 103 1", format: "500 ml", case: "6 × 500 ml", note: "Nordic berries and a little pine", vegan: true },
  { name: "Cloudberry Cream", color: "#d89b43", accent: "#ffe7b9", ean: "735 012 450 104 8", format: "500 ml", case: "6 × 500 ml", note: "Tart cloudberry, rich cream", vegan: false },
];

function Barcode({ value }: { value: string }) {
  return <div className="mt-5"><div className="h-9 w-full rounded-sm bg-[repeating-linear-gradient(90deg,#172019_0px,#172019_2px,transparent_2px,transparent_4px,#172019_4px,#172019_5px,transparent_5px,#172019_8px,#172019_8px,#172019_11px,transparent_11px,#172019_13px)]" /><p className="mt-1 text-center font-mono text-[8px] tracking-[0.12em] text-[#405244]">{value}</p></div>;
}

export default function BuyerKitDemo() {
  return (
    <main className="min-h-screen bg-[#f4f0e6] text-[#172019]">
      <header className="border-b border-[#172019]/15 bg-[#f4f0e6] px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold hover:opacity-70"><ArrowLeft className="h-4 w-4" /> Brandform</Link><p className="rounded-full border border-[#172019]/15 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#405244]">Concept buyer kit · Fictional brand</p></div></header>

      <section className="border-b border-[#172019]/15 px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1.02fr_.98fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#405244]">FJÄLLGLASS · Retail range 2026</p><h1 className="mt-5 max-w-xl font-serif text-5xl leading-[0.95] tracking-[-0.06em] sm:text-7xl">Small-batch ice cream for the good shelves.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#405244]">A fictional-but-realistic example of how a product brand can give a buyer the range, commercial facts and next step in one clear kit.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#range" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-[#172019] px-5 text-sm font-semibold text-[#f4f0e6]">Explore the range <ArrowRight className="h-4 w-4" /></a><a href="#order" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#172019]/20 px-5 text-sm font-semibold">Order details</a></div></div><div className="rounded-[2rem] bg-[#d5ddbd] p-6 sm:p-9"><div className="flex items-center justify-between"><span className="font-serif text-2xl tracking-tight">fjällglass</span><Snowflake className="h-6 w-6" /></div><div className="mt-14 grid grid-cols-4 gap-2"><div className="h-36 rounded-t-full bg-[#ed6d78] shadow-[inset_0_0_0_7px_rgba(255,255,255,.23)]" /><div className="mt-7 h-36 rounded-t-full bg-[#c9954e] shadow-[inset_0_0_0_7px_rgba(255,255,255,.23)]" /><div className="h-36 rounded-t-full bg-[#526bb6] shadow-[inset_0_0_0_7px_rgba(255,255,255,.23)]" /><div className="mt-7 h-36 rounded-t-full bg-[#d89b43] shadow-[inset_0_0_0_7px_rgba(255,255,255,.23)]" /></div><p className="mt-7 max-w-sm text-sm leading-6 text-[#405244]">Four Nordic flavours. One clean retailer story. Made for freezer doors, sample tables and the follow-up email.</p></div></div></section>

      <section className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-6xl"><div className="grid gap-8 border-b border-[#172019]/15 pb-12 md:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#405244]">The offer</p><h2 className="mt-4 font-serif text-4xl tracking-[-0.045em]">Premium ice cream with a clear point of view.</h2></div><div className="md:col-span-2"><p className="max-w-2xl text-lg leading-8 text-[#405244]">FJÄLLGLASS pairs Nordic ingredients with small-batch production. The range is designed for independent food stores, quality grocers and cafés that want a freezer people stop at.</p><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[Leaf,"Nordic ingredients","Straightforward flavour stories."],[Package,"Retail-ready format","500 ml tubs · six per case."],[Store,"Made for discovery","Strong shelf presence and easy sampling."]].map(([Icon,title,text]) => {const ItemIcon=Icon as typeof Leaf; return <div key={title as string} className="border-l border-[#172019]/20 pl-4"><ItemIcon className="h-4 w-4 text-[#405244]" /><p className="mt-3 font-semibold">{title as string}</p><p className="mt-1 text-sm leading-6 text-[#405244]">{text as string}</p></div>})}</div></div></div></div></section>

      <section id="range" className="border-y border-[#172019]/15 bg-[#e8e2d3] px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#405244]">Range overview</p><h2 className="mt-4 font-serif text-4xl tracking-[-0.045em] sm:text-5xl">Four reasons to open the freezer.</h2></div><p className="max-w-sm text-sm leading-6 text-[#405244]">Each product card combines the information a buyer needs to assess fit, list the SKU and place an order.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{products.map((product) => <article key={product.name} className="overflow-hidden rounded-2xl bg-[#f9f6ee] shadow-sm"><div className="p-5" style={{ backgroundColor: product.accent }}><div className="flex items-start justify-between"><span className="rounded-full bg-[#172019]/10 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[0.12em]">{product.vegan ? "Vegan" : "Dairy"}</span><span className="font-serif text-xl">fg</span></div><div className="mx-auto mt-9 flex h-36 w-28 items-center justify-center rounded-t-[2.5rem] border-[7px] border-white/35 shadow-[inset_0_0_0_1px_rgba(0,0,0,.08)]" style={{ backgroundColor: product.color, color: product.color === "#526bb6" ? "#ffffff" : "#172019" }}><span className="rotate-[-90deg] whitespace-nowrap text-[10px] font-bold uppercase tracking-[0.16em]">FJÄLLGLASS</span></div></div><div className="p-5"><h3 className="font-serif text-2xl tracking-[-0.04em]">{product.name}</h3><p className="mt-2 min-h-11 text-sm leading-5 text-[#405244]">{product.note}</p><dl className="mt-5 grid grid-cols-2 gap-y-2 border-y border-[#172019]/10 py-4 text-xs"><dt className="text-[#405244]">Format</dt><dd className="text-right font-semibold">{product.format}</dd><dt className="text-[#405244]">Case</dt><dd className="text-right font-semibold">{product.case}</dd></dl><Barcode value={product.ean} /></div></article>)}</div></div></section>

      <section id="order" className="px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#405244]">Retailer next step</p><h2 className="mt-4 font-serif text-4xl tracking-[-0.045em] sm:text-5xl">A buyer kit should end with an easy yes.</h2><p className="mt-5 max-w-md text-lg leading-8 text-[#405244]">This final section is where an actual brand would make sampling, a first order or a range discussion simple to start.</p></div><div className="rounded-3xl bg-[#172019] p-7 text-[#f4f0e6] sm:p-10"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#b8c99c]">First listing</p><h3 className="mt-3 font-serif text-4xl tracking-[-0.045em]">Start with the core four.</h3></div><MapPin className="h-6 w-6 text-[#b8c99c]" /></div><div className="mt-10 grid gap-4 sm:grid-cols-2"><div className="border-t border-white/15 pt-4"><p className="text-xs text-[#b8c99c]">Minimum opening order</p><p className="mt-2 text-xl font-semibold">4 cases</p><p className="mt-1 text-sm text-white/65">One case per flavour</p></div><div className="border-t border-white/15 pt-4"><p className="text-xs text-[#b8c99c]">Delivery window</p><p className="mt-2 text-xl font-semibold">3–5 weekdays</p><p className="mt-1 text-sm text-white/65">Stockholm example delivery</p></div></div><div className="mt-10 border-t border-white/15 pt-6"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#b8c99c]">Example buyer next steps</p><div className="mt-3 flex flex-col gap-3 sm:flex-row"><span className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-[#d5ddbd] px-5 text-sm font-semibold text-[#172019]">Request a tasting</span><span className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-white/20 px-5 text-sm font-semibold">Order the range <ArrowRight className="h-4 w-4" /></span></div><p className="mt-3 text-xs leading-5 text-white/60">Illustrative only. A real kit would link these actions to the brand&apos;s live sample and order process.</p></div></div></div></section>

      <footer className="border-t border-[#172019]/15 px-5 py-7 sm:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-2 text-xs text-[#405244] sm:flex-row sm:items-center sm:justify-between"><p>FJÄLLGLASS is a fictional brand created solely as a concept buyer kit.</p><Link href="/" className="font-semibold text-[#172019] hover:opacity-70">Made by Brandform</Link></div></footer>
    </main>
  );
}
